name: Hello World

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Say Hello!
        run: echo "Hello, World!"

      - name: list files
        run: ls -a

      - name:  Test oc
        run: |
          oc get pods || true 
          oc login -u kubeadmin https://api.crc.testing:6443
          oc get pods 
          crc stop
          crc delete -y
